import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import { sanityFetch } from "@/sanity/lib/fetch";
import { NAV_QUERY } from "@/sanity/lib/queries";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO: Update metadata with actual content
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nav = await sanityFetch<{ links: { label: string; href: string }[] }>({
    query: NAV_QUERY,
    tags: ["settings"],
  });

  return (
    <html
      lang="sv"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {nav?.links && <Navigation links={nav.links} />}
        {children}
      </body>
    </html>
  );
}
