import type { Metadata } from "next";
import { Bricolage_Grotesque, Capriola, Geist_Mono } from "next/font/google";
import { Header } from "@/components/Header";
import { sanityFetch } from "@/sanity/lib/fetch";
import { NAV_QUERY } from "@/sanity/lib/queries";
import "../globals.css";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-bricolage",
});

const capriola = Capriola({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-capriola",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO: Update metadata with actual content
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nav = await sanityFetch<{ links: { label: string; href: string }[] }>({
    query: NAV_QUERY,
    tags: ["settings"],
  });

  return (
    <html
      lang="sv"
      data-scroll-behavior="smooth"
      className={`${bricolage.variable} ${capriola.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header links={nav?.links} />

        <main className="flex-1">{children}</main>

        <footer className="bg-gray-100 text-center py-4">
          <p className="text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Print Campaign. All rights
            reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
