import type { Metadata } from "next";
import { Bricolage_Grotesque, Capriola, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Navigation } from "@/components/Navigation";
import { sanityFetch } from "@/sanity/lib/fetch";
import { NAV_QUERY } from "@/sanity/lib/queries";
import "../globals.css";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-bricolage",
});

const capriola = Capriola({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-capriola",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO: Update metadata with actual content
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nav = await sanityFetch<{ links: { label: string; href: string }[] }>({
    query: NAV_QUERY,
    tags: ["settings"],
  });

  return (
    <html
      lang="sv"
      data-scroll-behavior="smooth"
      className={`${bricolage.variable} ${capriola.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="fixed w-full top-0 z-1 py-sp-sm px-sp-sm lg:px-sp-lg flex items-start justify-between">
          <Link
            href="/"
            className="bg-white/80 backdrop-blur-xs rounded-full border-2 border-white"
          >
            {/* eslint-disable-next-line @next/next/no-img-element -- SVG, next/image doesn't support it */}
            <img
              src="/brand/logo_v1.svg"
              alt="Antirasistisk valstuga logotyp"
              className="h-16 md:h-20 animate-[spin_15s_linear_infinite] hover:[animation-play-state:paused]"
            />
          </Link>
          {nav?.links && <Navigation links={nav.links} />}
        </header>

        <main className="flex-1">{children}</main>

        <footer className="bg-gray-100 text-center py-4">
          <p className="text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Print Campaign. All rights
            reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
